name: cropsureconnect
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Firebase Services ---
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # --- State Management ---
  get: ^4.6.6
  provider: ^6.1.2

  # --- UI & Animations ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  animations: ^2.0.11
  fl_chart: ^0.68.0
  flutter_slidable: ^3.1.0

  # --- Utilities & Helpers ---
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^8.0.5
  camera: ^0.11.0+1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Declare your asset folders here for images and animations
  assets:
    - assets/images/
    - assets/lottie/
    # - assets/logos/ # Add other folders as needed