// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3SGNQLRWS88qgogVjs4ZAKNUMgmpZSL0',
    appId: '1:1030256388125:web:7d04d5d85e2a5ee442bef4',
    messagingSenderId: '1030256388125',
    projectId: 'cropsureconnect',
    authDomain: 'cropsureconnect.firebaseapp.com',
    storageBucket: 'cropsureconnect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhj94w-lgjwBp3-_h1EIDXeVV-2-7QGOM',
    appId: '1:1030256388125:android:5f1c62696664a1ad42bef4',
    messagingSenderId: '1030256388125',
    projectId: 'cropsureconnect',
    storageBucket: 'cropsureconnect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJUpcUDt7qZyAqFPa-BPgYK1jjqfAn98E',
    appId: '1:1030256388125:ios:19576bb65ba2b2b142bef4',
    messagingSenderId: '1030256388125',
    projectId: 'cropsureconnect',
    storageBucket: 'cropsureconnect.firebasestorage.app',
    iosBundleId: 'com.example.cropsureconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJUpcUDt7qZyAqFPa-BPgYK1jjqfAn98E',
    appId: '1:1030256388125:ios:19576bb65ba2b2b142bef4',
    messagingSenderId: '1030256388125',
    projectId: 'cropsureconnect',
    storageBucket: 'cropsureconnect.firebasestorage.app',
    iosBundleId: 'com.example.cropsureconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3SGNQLRWS88qgogVjs4ZAKNUMgmpZSL0',
    appId: '1:1030256388125:web:1c31390f8e1f8a3642bef4',
    messagingSenderId: '1030256388125',
    projectId: 'cropsureconnect',
    authDomain: 'cropsureconnect.firebaseapp.com',
    storageBucket: 'cropsureconnect.firebasestorage.app',
  );
}
